language: node_js
matrix:
  include:
  # Run ALL_BROWSERS only on the latest
  - node_js: '12'
    env: ALL_BROWSERS=true
  - node_js: '10'
env:
  global:
    - secure: "oKXUyhL0xwyCVVJxc5rI4y964sFsywqh7w4Ek0mYRI+xxg2534WahukEaP8vPkUW+xLKOYrzbJ7Ooblbr4/R+Lq0l3Ld5I5tzj4siv5BgQsHqrLOXlqJ5LNMBeH6grJSe66eRxU3ARsQkobbv5zyuFgQmNlvBqCaJ0eMLBz4k1BoeaReuNU6pl+Y1IomaAzb5OgrgRw0JXlGCkz4hEzvvgVl6pvqPn188zu5JNu5Umlsd3m+VJB2CL4jSyQwPhO5fZLGeCp9HGUNLN62kmbmMSm+pFP2iUlqxI14CWxrmnk8BC9dekEU4It6yIwfDyt1RPdxYD67VoFi6g2SfK5rp46j38YV3mZMdRnm6mw4q1I/OZEo0nmpyQnZzW2AwH7elc1bgyU9BGfL4JBem4A4ftUGGU5kocjSgRPu3tK4jIJzHThadjmtNc2j5nPkFEKDGc7Gyh1PlhWyImH7LvYpehhhbaBjb/x713VQzzzB4w+PyxvN02uvMsjhjqm+k45dcBtaBc9eW85f+I8uE/g9I/+XrM//p2G3STdsLuJHKhRNBzZwATwgWOEJYNdy8UO8cdu8u24g9Ig65HyhC01ZDfO97hmv/pfpc+T3JO8j2+pk2JbFIwBBjp/bUUBq1V+4kyDhOfWPlDjw7dn2gAfAssY97fFo3EUZC/wWxsfsRJg="
    - secure: "ZxuiZgMyFacKOZMn3FlUcVwYtz3vYuybOhiGGAX9nOqcIKv1dZFGpfUpiSlkSx7zVquEqRTctDyAXqH9Oaxz0DRBxg6qG0QQoa8EvLV+9qIcKju8okrhvusWuCU0LX9YNI5KkhtjL3ZSzfI4dwt2DvZ33cOHGrb1Dxm2fBtoE1BhtoXWmPBmYm6Qt+E2RRyeCxNx45gIIg50HKoiT4TuMp1D1RICNTtzp7lrs+5UL0AMsV3tvMyrErBYfVADihUAWqY0Txg8vooGFjJ5UgTH3IshgT9mNxzYWAZMXN5wUF+6qp6+F7H1N1QPYPHnTVYDFHBCgYWed/3SU0JQzcIDCEOGHGCdpdFCBkh4A084pe5U7X3gzrExq4ehl/ybE4pEgXhTx6onqYGQ1zEMVr4Dl5fTn9uiekzpwPuPZkFKj9FxMwtD1GIXwMHGK617x2CFqQxHsqdqyNmZe73mt0Edvd13Z3d18K+pOpEBkf8NQiA/T5tCpA8dNjK2YtiXyHpfPUqP/AxW/0O+0Z9+a8IGHdjCvP82o0UcnRAxbuGu59i/XtDwMV9mmbFXqd7aRizQLkZMGEmU+kxoJgj0hbmX7thNjvN678ju4yZpP4F+S91J3+sgOsXINmU58J/0HgDhFHV6aq4edD3eHFujTpQD16zpMa3s/AeGwNaIVg7817s="
addons:
  chrome: stable
  firefox: latest
script: npm run test ${ALL_BROWSERS+--browsers=all} && npm run lint
